### PR TITLE
[WIP] Add option to minify ServiceWorker file

### LINKED ISSUE #21: compress generated file
The generated service worker js file can be upwards of 24KB in size. Having the option to minimize or pass it through uglify would be great.

Unless I'm missing something, and it's possible to send the result of this plugin through to the `UglifyJS` plugin?

### PR DESCRIPTION
**Pull request by neeharv**
Fixes #21 

I have the initial setup done, but I'm struggling a bit to get the test code working.

There was some older test code lying around that I refactored slightly. While the code in its current form works, I am yet to finish the tests for the UglifyJS bits. I'll probably get some time over the weekend to wrap up the tests. 

@goldhand Could you do a preliminary review till then?

### CODE REVIEW

**Comment by goldhand** [comment]
Well done, good call using the generate method from sw-preache.
Sorry about the tests, I did some refactoring over the weekend and deleted `basic.test.js`, causing you some trouble. If you want to just submit the feature now, we can add tests in a separate pr. Whatever is easier for you.

**Comment by mikestead** [comment]
Any progress on this? Happy to help if needed

**Comment by neeharv** [comment]
@mikestead I should have this wrapped up by the weekend!

**Comment by goldhand** [comment]
@neeharv any chance you can push your whatever you have this weekend? I can try to finish this up

**Comment by neeharv** [comment]
@goldhand Ran into some rebasing issues with the tests. I'll finish this up over this weekend 🍻

**Comment by neeharv** [comment]
Rebased, fixed tests and cleaned up implementation. @goldhand this should be good to go 🍻

**Comment by goldhand** [comment]
Yayy! I'll take a look tonight and merge this bad boy. Thanks for all your work @neeharv , and just in time for the webpack 2 release!

**Comment by cevou** [comment]
It would be nice if the 7 commits could be squashed. It's nicer to only have one commit for the feature 😃

**Pull request merged**
