### PR TITLE
Allow to use [hash] on importScripts

### PR DESCRIPTION
**Pull request by Hosar**
Hi, this is the enhancement for this [issue](https://github.com/goldhand/sw-precache-webpack-plugin/issues/19). This is the first time I write a webpack plugin, so please let me know if it was ok, or if I could do something better.

### CODE REVIEW

**Comment by goldhand** [comment]
This looks great @Hosar , you were able to test this on your project I assume?

**Comment by Hosar** [comment]
Yes I tested on my own project. But I was curious on how to unit test that change. Do you plan to add mocha or something similar?

**Comment by goldhand** [comment]
I just meant did you test it on your project. Unit tests are on my todo... Just been busy but I hope to test this and merge it asap. Thanks for doing this.

**Comment by Hosar** [comment]
Sure, please let me know if I can provide any other help. I'm very interested in this project.

**Pull request merged**
