### PR TITLE
Update to webpack 3

### PR DESCRIPTION
**Pull request by lencioni**
Now that webpack 3 is out, I am bumping some versions in here
so folks can update. I don't know if any other changes are required
but I figured I'd get the ball rolling.

### CODE REVIEW

**Comment by goldhand** [comment]
Wow! That came out fast. Will def want to make sure we support it. Will check on this and read up on the release notes.

**Comment by lencioni** [comment]
If it is helpful, here are the release notes for webpack 3: https://github.com/webpack/webpack/releases/tag/v3.0.0

From what I've read, it seems that this new version is unlikely to cause many problems. 

> We marked this as a Major change because of internal breaking changes that could affect some plugins.
> So far we’ve seen 98% of users upgrade with no breaking functionality at all!!!

https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b

Let me know if there's anything I can do to help move this along.

**Comment by makenova** [comment]
Is there another PR that adds webpack 3 as a peer-dependency?

**Comment by lencioni** [comment]
It looks like mine was merged in https://github.com/goldhand/sw-precache-webpack-plugin/commit/c577cdff31d2b2366d65cd97eb9c964db4d33051 but not yet released.

**Comment by goldhand** [comment]
Just released in 0.11.4 :)

**Pull request closed without merging**
